### 1. Регистрация нового администратора
POST http://localhost:8000/register
Content-Type: application/json

{
    "username": "admin_user",
    "password": "admin_password",
    "roles": "admin"
}

### 2. Авторизация администратора и сохранение токена
POST http://localhost:8080/login
Content-Type: application/x-www-form-urlencoded

username=admin_user&password=admin_password

> {% client.global.set("admin_token", response.body.access_token) %}

### 3. Регистрация нового обычного пользователя
POST http://localhost:8080/register
Content-Type: application/json

{
    "username": "john_doe",
    "password": "secret_password",
    "roles": "user"
}

### 4. Авторизация обычного пользователя и сохранение токена
POST http://localhost:8080/login
Content-Type: application/x-www-form-urlencoded

username=john_doe&password=secret_password

> {% client.global.set("user_token", response.body.access_token) %}

### 5. Загрузка фильма как обычный пользователь
POST http://localhost:8080/upload_movie
Authorization: Bearer {{user_token}}
Content-Type: multipart/form-data

title=Inception
description=A mind-bending thriller.
file=@./path/to/inception.mp4

### 6. Отправка сообщения в Kafka как обычный пользователь
POST http://localhost:8080/send/
Authorization: Bearer {{user_token}}
Content-Type: application/json

{
    "action": "upload",
    "movie_id": 1
}

### 7.
POST http://localhost:8000/admin/upload_movie
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsImlkIjoyLCJyb2xlcyI6WyJhZG1pbiJdLCJleHAiOjE3MzQ4OTgzNzd9.t4Odywv6txABaZ2VQGI_mR8fj9M3OfX1cdRLX1C7LE8
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="title"

My Movie
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="description"

This is a description of the movie.
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="2024-12-04 18-17-45.mp4"
Content-Type: video/mp4

< C:\Users\Asus\PycharmProjects\fastapi-video-player\2024-12-04 18-17-45.mp4
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###
