@base_url = http://127.0.0.1:8000

### Получение JWT-токена
POST {{base_url}}/token
Content-Type: application/x-www-form-urlencoded

username=johndoe&password=secret

### Отправка сообщения в Kafka
POST {{base_url}}/send/
Content-Type: application/json
#токен после Bearer нужно заменить на свой, перед запросом необходимо его получить
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqb2huZG9lIiwiZXhwIjoxNzMzMTQ3OTk3fQ.OcCIhQhLE1TCWnlMbjeSFWz5B4anunql1kQKnK07mik

{
  "id": 9997555,
  "timestamp": 17002133244000.0,
  "message": "Тестовое NEW сообщение"
}
